export type Locale = "ko" | "en";
const KEY = "reversix-language";
let locale: Locale = readLocale();
function readLocale(): Locale {
  try { const saved = localStorage.getItem(KEY); if (saved === "ko" || saved === "en") return saved; } catch {}
  return "en";
}
export function getLocale() { return locale; }
export function setLocale(next: Locale) {
  locale = next;
  try { localStorage.setItem(KEY, next); } catch {}
  document.documentElement.lang = next;
  document.querySelector<HTMLMetaElement>('meta[name="description"]')?.setAttribute("content", t("meta.description"));
}
const ko: Record<string, string> = {
  "meta.description":"REVERSIX! 한 턴에 두 수를 두고 정확히 여섯 개로 체크를 거는 2인용 리버시 전략 게임.",
  "lobby.create":"새로운 방 만들기","lobby.joinLabel":"코드를 사용하여 들어가기","lobby.code":"6자리 코드","lobby.join":"들어가기","lobby.how":"게임 방법","lobby.settings":"설정","lobby.creating":"방 만드는 중","lobby.joining":"방으로 들어가는 중","lobby.reconnecting":"다시 연결하는 중","lobby.unconfigured":"온라인 연결이 설정되어있지 않습니다. 호스트의 firebase 셋업이 설정되어 있지 않습니다. 잠시 후 다시 시도해 주세요.",
  "game.room":"{code}번 방","game.copy":"복사하기","game.copied":"복사됨","game.select":"코드를 선택해 주세요","game.waiting":"상대방을 기다리는 중","game.draw":"비겼다..!","game.win":"이겼다!!","game.lose":"졌다...","game.turn":"{color} 차례 - {move} / {total}","game.black":"흑돌","game.white":"백돌","game.check":"체크!","game.defend":"체크! 방어하세요!","game.survived":"상대가 방어를 실패했습니다!","game.remained":"방어를 실패했습니다...","game.you":"당신은 {color}입니다. 흑 {black}개 / 백 {white}개","game.connection":"인터넷 연결 에러","game.disconnected":"상대의 연결이 해제되어 있습니다","game.back":"로비로 돌아가기","game.undo":"되돌리기","game.soundOn":"소리 켜기","game.soundOff":"소리 끄기",
  "settings.title":"설정","settings.language":"언어","settings.sound":"소리","settings.on":"켜기","settings.off":"끄기","settings.close":"닫기",
  "chat.title":"채팅","chat.choose":"메시지 선택...","chat.me":"나","chat.opponent":"상대",
  "tutorial.count":"게임 방법 · {page} / {total}","tutorial.back":"이전","tutorial.next":"다음","tutorial.play":"완료","tutorial.closeAria":"게임 방법 닫기",
  "tutorial.step1.title":"1. 뒤집기","tutorial.step1.p1":"돌을 놓아 상대 돌 하나 이상을 내 돌 사이에 끼우면, 끼인 돌이 내 색으로 뒤집힙니다.","tutorial.step1.caption":"놓기 전 → 놓은 후 · 가로·세로·대각선 8방향에 적용됩니다.",
  "tutorial.step2.title":"2. 한 턴에 두 수","tutorial.step2.p1":"흑의 첫 턴만 한 수를 둡니다. 그다음부터는 양쪽 모두 한 턴에 두 수를 둡니다.","tutorial.step2.p2":"각 수를 둔 직후 뒤집기가 먼저 적용됩니다. 첫 번째 수의 결과에 따라 두 번째 수의 합법수가 달라질 수 있으며, 둘 곳이 없으면 두 번째 수는 생략됩니다.","tutorial.step2.caption":"1수 → 뒤집기 → 2수 → 뒤집기",
  "tutorial.step3.title":"3. SIX 만들기","tutorial.step3.p1":"가로·세로·대각선 중 한 방향으로 자기 돌을 정확히 6개 연결하면 SIX가 됩니다.","tutorial.step3.p2":"5개는 아무 효과가 없고, 7개 이상도 SIX로 인정되지 않습니다.","tutorial.step3.caption":"정확히 6개 → 체크 · 7개 이상 → 체크 아님",
  "tutorial.step4.title":"4. 체크!","tutorial.step4.p1":"정확히 6개를 만들었다고 바로 이기는 것은 아닙니다. 턴이 끝날 때 상대에게 체크를 겁니다.","tutorial.step4.p2":"상대는 다음 한 턴 전체를 사용해 모든 SIX를 끊어야 합니다. 한 턴의 첫 번째 수만 둔 중간 상태에서는 체크를 판정하지 않습니다.","tutorial.step4.caption":"흑 체크 → 백이 SIX를 끊어 방어",
  "tutorial.step5.title":"5. SIX 방어하기","tutorial.step5.p1":"방어 턴이 끝났을 때 상대의 SIX가 하나라도 남아 있으면 패배합니다. 여러 개라면 전부 끊어야 합니다.","tutorial.step5.p2":"체크를 막으면서 동시에 자신의 SIX를 만들면 카운터 체크가 됩니다.","tutorial.step5.p3":"둘 수 있는 곳이 없으면 패스합니다. 체크 상태에서 패스하면 패배합니다. 그 외에는 양쪽이 연속으로 패스하면 돌 개수로 승패를 정합니다.","tutorial.step5.caption":"흑 SIX 방어 + 백 SIX 완성 → 카운터 체크",
  "board.label":"10×10 게임판","board.cell":"{row}행 {column}열: {state}","board.empty":"빈칸","board.legal":"둘 수 있는 칸","board.forbidden":"더블 SIX 규칙으로 둘 수 없는 칸","board.first":"첫 번째 새 흑돌","board.second":"두 번째 새 흑돌",
};
const en: Record<string, string> = {
  "meta.description":"REVERSIX! A private two-player Reversi game with two moves and SIX checks.","lobby.create":"CREATE PRIVATE GAME","lobby.joinLabel":"JOIN PRIVATE GAME","lobby.code":"6-LETTER CODE","lobby.join":"JOIN","lobby.how":"HOW TO PLAY","lobby.settings":"SETTINGS","lobby.creating":"CREATING ROOM","lobby.joining":"JOINING ROOM","lobby.reconnecting":"RECONNECTING TO ROOM","lobby.unconfigured":"ONLINE PLAY IS NOT CONFIGURED. The host must finish Firebase setup.","game.room":"ROOM {code}","game.copy":"COPY","game.copied":"COPIED","game.select":"SELECT CODE","game.waiting":"WAITING FOR PLAYER","game.draw":"DRAW","game.win":"YOU WIN","game.lose":"YOU LOSE","game.turn":"{color}'S TURN — MOVE {move} / {total}","game.black":"BLACK","game.white":"WHITE","game.check":"CHECK!","game.defend":"CHECK! YOU ARE IN CHECK","game.survived":"SIX SURVIVED","game.remained":"SIX REMAINED","game.you":"YOU ARE {color} · BLACK {black} / WHITE {white}","game.connection":"CONNECTION LOST — RECONNECTING","game.disconnected":"OPPONENT DISCONNECTED","game.back":"BACK TO LOBBY","game.undo":"UNDO","game.soundOn":"SOUND ON","game.soundOff":"SOUND OFF","settings.title":"SETTINGS","settings.language":"LANGUAGE","settings.sound":"SOUND","settings.on":"ON","settings.off":"OFF","settings.close":"CLOSE","tutorial.count":"HOW TO PLAY · {page} / {total}","tutorial.back":"BACK","tutorial.next":"NEXT","tutorial.play":"PLAY","tutorial.closeAria":"Close how to play","board.label":"10 by 10 game board","board.cell":"Row {row}, column {column}: {state}","board.empty":"empty","board.legal":"legal move","board.first":"first new black stone","board.second":"second new black stone",
  "chat.title":"CHAT","chat.choose":"CHOOSE MESSAGE...","chat.me":"ME","chat.opponent":"OPPONENT",
  "tutorial.step1.title":"1. FLIP","tutorial.step1.p1":"Place a stone so that one or more opponent stones are trapped between your stones. Those stones flip to your color.","tutorial.step1.caption":"BEFORE → AFTER · Works in all eight directions.",
  "tutorial.step2.title":"2. TWO MOVES","tutorial.step2.p1":"Black places one stone on the first turn. After that, each player places two stones per turn.","tutorial.step2.p2":"Flip after each move. The first move can change where the second move is legal. If no legal move remains, that move is skipped.","tutorial.step2.caption":"MOVE 1 → FLIP → MOVE 2 → FLIP",
  "tutorial.step3.title":"3. MAKE SIX","tutorial.step3.p1":"Connect exactly six of your stones in a horizontal, vertical, or diagonal line.","tutorial.step3.p2":"Five does nothing. Seven or more does not count.","tutorial.step3.caption":"EXACTLY 6 → CHECK · 7 OR MORE → NO CHECK",
  "tutorial.step4.title":"4. CHECK!","tutorial.step4.p1":"Completing a line of six does not win immediately. It puts your opponent in CHECK at the end of your turn.","tutorial.step4.p2":"Your opponent gets their next full turn to break every SIX. CHECK is not declared halfway through a two-move turn.","tutorial.step4.caption":"BLACK CHECK → WHITE BREAKS THE LINE",
  "tutorial.step5.title":"5. BREAK THE SIX","tutorial.step5.p1":"If at least one opponent SIX still exists at the end of your turn, you lose. Break all of them.","tutorial.step5.p2":"Breaking the CHECK while creating your own SIX creates a COUNTER CHECK.","tutorial.step5.p3":"No legal move? PASS. Passing while in CHECK loses. Otherwise, two consecutive passes end the game by stone count.","tutorial.step5.caption":"BLACK SIX BROKEN + WHITE SIX → COUNTER CHECK",
};
export function t(key: string, vars: Record<string,string|number> = {}) { const value = (locale === "ko" ? ko[key] : en[key]) ?? en[key] ?? key; return value.replace(/\{(\w+)\}/g, (_, key) => String(vars[key] ?? "")); }
const events: Record<string, [string,string]> = {"PLAYER JOINED":["PLAYER JOINED","상대방이 들어왔습니다!"],"CHECK!":["CHECK!","체크!"],"COUNTER CHECK!":["COUNTER CHECK!","카운터 체크!"],"CHECK DEFENDED":["CHECK DEFENDED","체크 해제!"],"OPPONENT DISCONNECTED":["OPPONENT DISCONNECTED","상대방의 연결이 끊어졌습니다"],"OPPONENT RECONNECTED":["OPPONENT RECONNECTED","상대방의 연결이 돌아왔습니다."],"BLACK PASS":["BLACK PASS","흑돌을 더 이상 둘 곳이 없습니다."],"WHITE PASS":["WHITE PASS","백돌을 더 이상 둘 곳이 없습니다."],"BLACK SECOND MOVE SKIPPED":["BLACK SECOND MOVE SKIPPED","흑돌을 더 이상 둘 곳이 없습니다."],"WHITE SECOND MOVE SKIPPED":["WHITE SECOND MOVE SKIPPED","백돌을 더 이상 둘 곳이 없습니다."]};
export function localizeEvent(event:string) { return events[event]?.[locale === "ko" ? 1 : 0] ?? event; }
const errors: Record<string,string> = {"ROOM NOT FOUND":"방을 찾을 수 없습니다. 다시 한번 확인해 주세요.","ILLEGAL MOVE":"둘 수 없는 곳입니다.","UNDO IS NOT AVAILABLE":"되돌리기를 할 수 없어요.","ROOM FULL":"누가 이 방에 이미 있어요..!","NOT YOUR TURN":"아직 당신의 차례가 아니에요!","STATE CHANGED — TRY AGAIN":"서버 게임 revision이 바뀌었습니다. 다시 시도해 주세요.","ENTER A VALID 6-CHARACTER CODE":"6자리 코드를 입력해 주세요!!"};
export function localizeError(error:string) { if (locale === "en") return errors[error] ? error : "A NETWORK ERROR OCCURRED. PLEASE TRY AGAIN LATER."; return errors[error] ?? "네트워크 오류가 발생했습니다. 잠시 후 다시 시도해 주세요."; }
